name: Output Event Details on "Issues" Project
on: workflow_dispatch
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output Message
        run: echo "${{ toJson(github) }}"
      - name: Issues Message
        run: echo "${{ toJson(github.event.issue) }}"